package policy

import (
	"math"
	"regexp"
	"strings"
)

// This file ports the control plane's AI Guard detector suite
// (backend/app/detectors/*) into the inline Go agent so the full breadth of
// detectors enforces inline, not just the prompt-injection/jailbreak
// heuristic. Detectors are deterministic and allocation-light. Wire parity:
// detector names/categories MUST match the Python suite so a guardrail policy
// generated by the control plane (the "Policy Generator") applies identically
// inline.

// DetectorContext carries optional operator signals (mirrors the Python
// DetectorContext / policy content_filters).
type DetectorContext struct {
	Direction        Direction
	AllowedTopics    []string
	CompetitorTerms  []string
	BrandTerms       []string
	AllowedLanguages []string
	Extra            map[string]any
}

// DetectorResult is one detector's calibrated verdict.
type DetectorResult struct {
	Name       string
	Category   string
	Confidence float64
	Severity   Severity
	Evidence   map[string]any
}

// Detector is a single content detector.
type Detector struct {
	Name             string
	Category         string
	DefaultThreshold float64
	Severity         Severity
	Directions       []Direction // empty => both
	Detect           func(text string, ctx DetectorContext) DetectorResult
}

// Applies reports whether the detector runs for the given direction.
func (d Detector) Applies(dir Direction) bool {
	if len(d.Directions) == 0 {
		return true
	}
	for _, x := range d.Directions {
		if x == dir {
			return true
		}
	}
	return false
}

func clamp01(x float64) float64 {
	if x < 0 {
		return 0
	}
	if x > 1 {
		return 1
	}
	return math.Round(x*10000) / 10000
}

func res(name, cat string, conf float64, sev Severity, ev map[string]any) DetectorResult {
	if ev == nil {
		ev = map[string]any{}
	}
	return DetectorResult{Name: name, Category: cat, Confidence: clamp01(conf), Severity: sev, Evidence: ev}
}

// ───────────────────────────── shared helpers

var wordRe = regexp.MustCompile(`[A-Za-z']+`)
var tokenRe = regexp.MustCompile(`[\p{L}\p{N}_]+`)

var commonEN = func() map[string]struct{} {
	m := map[string]struct{}{}
	for _, w := range strings.Fields(`the be to of and a in that have i it for not on with he as you do at this but his by from they we say her she or an will my one all would there their what so up out if about who get which go me when make can like time no just him know take people into year your good some could them see other than then now look only come its over think also back after use two how our work first well way even new want because any these give day most us is are was were been has had please help write code data model security policy prompt response user system company report should need using able`) {
		m[w] = struct{}{}
	}
	return m
}()

func words(s string) []string  { return wordRe.FindAllString(s, -1) }
func tokens(s string) []string { return tokenRe.FindAllString(strings.ToLower(s), -1) }

func shannonEntropy(s string) float64 {
	if s == "" {
		return 0
	}
	counts := map[rune]float64{}
	for _, r := range s {
		counts[r]++
	}
	n := float64(len([]rune(s)))
	var e float64
	for _, c := range counts {
		p := c / n
		e -= p * math.Log2(p)
	}
	return e
}

func vowelRatio(w string) float64 {
	if w == "" {
		return 0
	}
	v := 0
	for _, r := range strings.ToLower(w) {
		switch r {
		case 'a', 'e', 'i', 'o', 'u':
			v++
		}
	}
	return float64(v) / float64(len(w))
}

func englishWordRatio(s string) float64 {
	ws := words(s)
	if len(ws) == 0 {
		return 0
	}
	hits := 0
	for _, w := range ws {
		if _, ok := commonEN[strings.ToLower(w)]; ok {
			hits++
		}
	}
	return float64(hits) / float64(len(ws))
}

var obfReplacer = strings.NewReplacer("0", "o", "1", "i", "3", "e", "4", "a", "5", "s", "7", "t", "@", "a", "$", "s")
var obfSepRe = regexp.MustCompile(`([\p{L}\p{N}])[\.\-_\*\s]([\p{L}\p{N}])`)

func collapseObfuscation(s string) string {
	low := obfReplacer.Replace(strings.ToLower(s))
	// collapse single separators between word chars, run twice for overlaps
	for i := 0; i < 2; i++ {
		low = obfSepRe.ReplaceAllString(low, "$1$2")
	}
	return low
}

func maxF(a, b float64) float64 {
	if a > b {
		return a
	}
	return b
}
