{{- if and (not .Values.agentApiKey.existingSecret) .Values.agentApiKey.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}-api-key
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.agentApiKey.apiKey | quote }}
{{- end -}}
