"""bcrypt hashing for machine credentials — the one place bcrypt is called.

Every secret this platform stores as a hash (API keys, SCIM bearer tokens) goes
through :func:`hash_secret` and :func:`verify_secret`. Call sites do not import
``bcrypt`` and do not encode, salt, or choose a cost factor themselves; keeping
those decisions in one module is what makes them auditable and changeable.

Why this module exists at all
-----------------------------
Hashing used to go through ``passlib.hash.bcrypt``. passlib 1.7.4 is its last
release (2020) and it is incompatible with bcrypt 5.x: passlib probes its
backend on first use with a deliberately over-72-byte secret (``detect_wrap_bug``),
and bcrypt 5.0 changed ``hashpw`` to *raise* on such input instead of silently
truncating. The probe therefore explodes on the FIRST hash or verify of the
process, for every input, no matter how short. That pinned the platform to
``bcrypt<5.0`` and left a dead, unmaintained dependency in the credential path.
Calling ``bcrypt`` directly removes both problems; the hash format is unchanged.

Format compatibility: this module produces ``$2b$12$…`` — byte-for-byte the same
scheme, ident and cost factor passlib produced with its defaults — so hashes
written before this change verify unchanged, and hashes written after it would
verify under the old code too. There is no migration and no dual-read window.

The 72-byte limit: why we REJECT rather than pre-hash
-----------------------------------------------------
bcrypt only ever consumed the first 72 bytes of a secret. bcrypt 5.0 stopped
hiding that by raising instead of truncating, which is an improvement: silent
truncation means a 200-byte secret and a different 200-byte secret sharing a
72-byte prefix authenticate each other.

The two honest responses are (a) reject over-length secrets, or (b) SHA-256
pre-hash so any length maps into 72 bytes. We reject, because every secret that
reaches this module is machine-generated by this codebase and is comfortably
under the limit:

* API keys   — ``app/auth/api_key_service.py``: 8-char prefix + ``.`` +
  ``token_urlsafe(32)``  → 52 ASCII bytes.
* SCIM tokens — ``app/scim/auth.py``: ``"scim_"`` + ``token_urlsafe(40)``
  → 59 ASCII bytes.

Both leave ~20 bytes of headroom. Pre-hashing would buy capacity nobody uses
while permanently adding a construction we could never remove: once a single
hash is written over a SHA-256 digest, every future verify must reproduce that
exact pre-hash forever, and the ``$2b$`` string on disk does not record which
scheme made it. Rejecting keeps the stored artifact self-describing.

If a future caller genuinely needs to hash a user-chosen passphrase of unbounded
length, add a *separate*, explicitly-named function with its own prefix or
storage marker. Do not quietly widen this one.
"""

from __future__ import annotations

import bcrypt

__all__ = ["MAX_SECRET_BYTES", "SecretTooLongError", "hash_secret", "verify_secret"]

# bcrypt's own hard limit. Not a policy knob — the algorithm consumes no more
# than this, and bcrypt 5.x raises rather than truncating past it.
MAX_SECRET_BYTES = 72

# Matches passlib's historical default (``$2b$``, 12 rounds), which is also
# ``bcrypt.gensalt()``'s default. Stated explicitly so a change to either
# upstream default is a visible diff here rather than a silent re-costing.
_ROUNDS = 12
_IDENT = b"2b"


class SecretTooLongError(ValueError):
    """Raised by :func:`hash_secret` for a secret over :data:`MAX_SECRET_BYTES`.

    Subclasses ``ValueError`` so existing ``except ValueError`` handlers around
    the old passlib calls keep behaving sensibly.
    """


def hash_secret(secret: str) -> str:
    """Hash ``secret`` with bcrypt and return the ``$2b$12$…`` string.

    Raises :class:`SecretTooLongError` if ``secret`` encodes to more than
    :data:`MAX_SECRET_BYTES` UTF-8 bytes. The limit is on BYTES, not characters:
    a 40-character string of non-ASCII text can exceed it while a 70-character
    ASCII one does not. Refusing is deliberate — see the module docstring.
    """
    encoded = secret.encode("utf-8")
    if len(encoded) > MAX_SECRET_BYTES:
        # Report the length, never the secret.
        raise SecretTooLongError(
            f"secret is {len(encoded)} UTF-8 bytes; bcrypt accepts at most "
            f"{MAX_SECRET_BYTES}. Generate a shorter credential rather than "
            "truncating — a truncated secret silently collides with every "
            "other secret sharing its first 72 bytes."
        )
    return bcrypt.hashpw(encoded, bcrypt.gensalt(rounds=_ROUNDS, prefix=_IDENT)).decode("ascii")


def verify_secret(secret: str, hashed: str) -> bool:
    """Return whether ``secret`` matches ``hashed``. Never raises.

    Total by design: this runs on the unauthenticated path with attacker-chosen
    input, so a malformed stored hash, a non-bcrypt string, or an over-length
    presented secret must all be an ordinary authentication failure rather than
    a 500 that distinguishes itself from a wrong password.

    An over-length secret returns ``False`` rather than raising: :func:`hash_secret`
    refuses such secrets, so no hash this platform ever wrote can correspond to
    one, and a caller presenting 5 KB of input is failing auth, not hitting a bug.
    """
    encoded = secret.encode("utf-8")
    if len(encoded) > MAX_SECRET_BYTES:
        return False
    try:
        # bcrypt.checkpw is constant-time in the comparison of the derived hash.
        return bcrypt.checkpw(encoded, hashed.encode("utf-8"))
    except (ValueError, TypeError):
        # Malformed / empty / non-bcrypt stored hash.
        return False
